import os
import re
from core.models import Task, TaskStatus
from core.task_manager import update_task_status
from core.pm_llm import _call_pm_llm
from core.git_agent import GitAgent

def extract_code_blocks(text: str) -> dict[str, str]:
    """
    Extract file paths and code blocks from LLM markdown output.
    Expects format:
    ```filename.py
    print('hello')
    ```
    """
    files = {}
    # Regex to find ```filepath\ncode...```
    pattern = r"```([a-zA-Z0-9_\-\./\\]+)\n(.*?)```"
    matches = re.finditer(pattern, text, re.DOTALL)
    for match in matches:
        filepath = match.group(1).strip()
        code = match.group(2)
        # some models output ```python filepath
        if filepath.startswith(("python", "js", "ts", "html", "css", "sql")):
            parts = filepath.split()
            if len(parts) > 1:
                filepath = parts[1]
            else:
                filepath = f"new_file_{len(files)}.txt"
        files[filepath] = code
    return files

async def execute_task_with_swarm(task_id: int):
    """
    Spins up the Worker Agent for the task, generates code, 
    and uses the GitAgent to PR it.
    """
    print(f"Swarm: Assigning Task #{task_id} to a Worker Agent...")
    
    # 1. Fetch Task Info
    from db.connection import get_connection
    async with get_connection() as conn:
        row = await conn.fetchrow("SELECT * FROM tasks WHERE id = $1", task_id)
        if not row:
            raise ValueError(f"Task {task_id} not found.")
        task = dict(row)

    project_id = task['project_id']
    title = task['title']
    brief = task['brief']
    ac = task['acceptance_criteria']
    repo_url = task.get('repo_url')
    
    if not repo_url:
        print(f"Swarm: Task #{task_id} has no repo_url. Cannot run DevOps agent.")
        await update_task_status(task_id, TaskStatus.FAILED, assigned_agent="Swarm Error")
        return

    # 2. Worker Agent LLM Call
    system_prompt = f"""You are an elite Autonomous AI Developer specializing in {task['category']} tasks.
Your job is to read the task description and write ALL the necessary code to fulfill the acceptance criteria.

Output your code using standard markdown code blocks, but place the EXACT FILEPATH on the first line after the backticks.
Example:
```src/main.py
print("Hello World")
```

Write all the files needed to complete this task."""

    user_prompt = f"""Project ID: {project_id}
Task: {title}
Description: {brief}

Acceptance Criteria:
{ac}

Please write the code for this task:"""

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    
    await update_task_status(task_id, TaskStatus.IN_PROGRESS, assigned_agent="Worker Agent")
    print(f"Swarm: Worker Agent is coding...")
    
    try:
        raw_code_response = _call_pm_llm(messages)
        files_to_write = extract_code_blocks(raw_code_response)
        
        if not files_to_write:
            raise ValueError("LLM returned no code blocks.")
            
        print(f"Swarm: Worker Agent generated {len(files_to_write)} files.")
        
        # 3. DevOps Agent Pipeline
        workspace_dir = f"/tmp/orchestrator_workspace_{project_id}"
        devops = GitAgent(repo_url=repo_url, working_dir=workspace_dir)
        
        # Clone repo
        if not os.path.exists(workspace_dir):
            await devops.clone_repo()
            
        branch_name = f"feature/task-{task_id}-{title.lower().replace(' ', '-')}"
        devops.create_branch(branch_name)
        
        # Write files
        for filepath, code in files_to_write.items():
            full_path = os.path.join(workspace_dir, filepath)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(code)
                
        # Commit and Push
        commit_msg = f"Task #{task_id}: {title}\n\n{brief}"
        devops.commit_changes(commit_msg)
        devops.push_branch(branch_name)
        
        # Open PR
        pr_url = await devops.create_pull_request(
            branch_name=branch_name,
            title=f"Feature: {title} (Task #{task_id})",
            body=f"This PR was automatically generated by the Autonomous Swarm.\n\n**Brief:**\n{brief}\n\n**Acceptance Criteria:**\n{ac}"
        )
        print(f"Swarm: PR Created! {pr_url}")
        
        # 4. QA Agent (Optional Auto-Merge for low tier tasks)
        if task['complexity_score'] <= 3:
            print("Swarm: QA Agent Auto-Approving PR...")
            # In a real system, the QA agent would read the diff here. 
            # We assume it passes for MVP.
            pr_number = int(pr_url.split('/')[-1])
            await devops.auto_merge_pr(pr_number, commit_msg)
            
        await update_task_status(task_id, TaskStatus.COMPLETED)
        
    except Exception as e:
        print(f"Swarm Error on Task #{task_id}: {e}")
        await update_task_status(task_id, TaskStatus.FAILED)
